- hosts: localhost
  gather_facts: no
  strategy: free
  vars_files:
    - vars.yml
  tasks:
    - include_tasks: provisioning/azure/azure-elk-res-creation.yml
    - name: set target host
      set_fact:
        target_host: 'Type_{{ namespace }}-elksvr'
    - name: set username
      set_fact:
        username: '{{ admin_username }}'
    - meta: refresh_inventory


- hosts: "{{ hostvars['localhost']['target_host'] }}"
  remote_user: "{{ hostvars['localhost']['username'] }}"
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  strategy: free
  vars_files:
    - vars.yml
  tasks:
    - include_tasks: configuration/hackazon-elksvr.yml
